export const ADD_CURRENT_POST = 'ADD_CURRENT_POST';
export const CLEAR_CURRENT_POST = 'CLEAR_CURRENT_POST';
export const UPDATE_CURRENT_POST_AUTHOR = 'UPDATE_CURRENT_POST_AUTHOR';
export const UPDATE_CURRENT_POST_BODY = 'UPDATE_CURRENT_POST_BODY';
export const UPDATE_CURRENT_POST_CATEGORY = 'UPDATE_CURRENT_POST_CATEGORY';
export const UPDATE_CURRENT_POST_TITLE = 'UPDATE_CURRENT_POST_TITLE';
